import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import Link from 'next/link'
import image1 from './img/frontimage.jpg';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NavalWar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>


      <main className={styles.main}>
        <div className={styles.titre}>
            <p>
            NavalWar
            </p>

        </div>
        <div className={styles.description}>
          <p>
            NavalWar's Game Description.........
          </p>
        </div>

        <div className={styles.center}>
        <Image className={styles.logo} src={image1} alt="image1" width="900"/>
        </div>

        <div className={styles.grid}>
          <Link
            href="manuel"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            MANUEL DE REGELE DE JEU<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Guide de jeu super détaillé
            </p>
          </Link>

          <a
            href="https://www.huya.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            START THE BATTLE!<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Dépêchez-vous
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              EXIT <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Merde
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            Game comment section <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            nous disputons
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
